# This is a basic workflow to help you get started with Actions

name: sure.sample1 firstwebsite

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x,10.x,12.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: installing node
      run: actions/setup-node@v1
      with:
          node-version: ${{ matrix.node-version }}
      - name: installing surge
      run: npm install --global surge
    # Runs a single command using the runners shell
    - name: deploying using surge
      run: surge ./ delmewaqas.surge.sh --token ${{ secrets.MY_TOKEN }}
